### ISSUE TITLE
Убрать кнопку Войти с помощью Facebook 

### ISSUE THREAD

**Issue by racc-oo-n** [Newsi/talk#12]
**url:** https://www.nur.stage.systools.pro/1690787-sagintaev-predlozil.html
**steps to reproduce:**
1. Перейти в любой пост 
2. Нажать "Войти для участия в беседе"
3. Обратить внимание на кнопку Войти с помощью Facebook

**actual:** [Блок комментариев] Убрать кнопку Войти с помощью Facebook (нет возможности входа с помощью Facebook) 
**screen:** https://www.screencast.com/t/guKHCZkx5
**expected:** Кнопка Войти с помощью Facebook отсутствует

**Comment by svitlanamykolaienko** [comment]
Исправлено
https://www.screencast.com/t/ucKhRkAfEam
