### ISSUE TITLE
Кнопка "Показать больше ответов" не работает

### ISSUE THREAD

**Issue by odynokov** [Newsi/talk#15]
### Expected behavior
Кнопка "Показать больше ответов" работает: при нажатии подгружаются остальные ответы.

### Actual behavior
Кнопка "Показать больше ответов" не работает: при нажатии не подгружаются остальные ответы. В консоли высвечивается ошибка.

<img width="952" alt="screen shot 2017-12-18 at 4 45 06 pm" src="https://user-images.githubusercontent.com/8394157/34111621-f00ac672-e412-11e7-8706-847a6cd9b77c.png">

### Steps to reproduce behavior
Убедиться, что есть более 3 ответов к комментарию. Нажать кнопку "Показать больше ответов".

**Comment by racc-oo-n** [comment]
это ещё актуальная задача?

**Comment by odynokov** [comment]
Да. Обращаю внимание, что речь не о первых комментариях, а об ответах (вложенных).

**Comment by racc-oo-n** [comment]
Переехало в jira
