### ISSUE TITLE
Название статьи (истории) в карточке с комментарием

### ISSUE THREAD

**Issue by odynokov** [Newsi/talk#17]
Иногда в карточке с комментарием в админке подтягивается не заголовок статьи, а заголовок главной страницы в пункте "История".

![33](https://user-images.githubusercontent.com/8394157/34285278-3bb6782a-e6e1-11e7-9dba-e83dc095150f.JPG)

В истории должен быть заголовок статьи.

**Comment by racc-oo-n** [comment]
moved to jira
