### ISSUE TITLE
Добавить аналитику для СМС

### ISSUE THREAD

**Issue by racc-oo-n** [Newsi/talk#26]
Попытки отправить СМС сообщения со статусами об успешности нужно писать в редис.
В `api/metrics/index.js` устанавливать эти значения.

**Comment by odynokov** [comment]
@yeo-gen собирается сделать общий Redis. Так ведь?

**Comment by yeo-gen** [comment]
Спільний redis вже готовий 😀
Після деплоя всі інстанси talk будуть використовувати спільний redis

**Comment by odynokov** [comment]
Ооооо.
@yeo-gen Правильно будет писать попытки отправить СМС в Redis?

**Comment by yeo-gen** [comment]
Пропоную наступну схему - всі критичні дані які потрібно зберегти йдуть в монгу, якщо нам не жалко їх втратити часом при ребуті редіса ( скажемо раз на тиждень або місяць) то краще зберігати в редіса.
Спроби відправки звучить як тимчасова річ тому я б її клавіатури в редіса і не навантажував лишніми запитами монгу.

**Comment by racc-oo-n** [comment]
Оки, поменяла описание задачи
