### ISSUE TITLE
Логирование действий модератора в админке

### ISSUE THREAD

**Issue by racc-oo-n** [Newsi/talk#3]
Ветка `nur`

Админка находится по адресу http://127.0.0.1:3000/admin

В админке по адресу Community -> People (http://127.0.0.1:3000/admin/community/people) есть таблица всех пользователей, при клике по имени пользователя открывается панель сбоку с информацией о пользователе и списком всех комментариев, которые он оставил.

В эту таблицу нужно добавить ещё одну колонку справа – Activity.

![pasted image at 2017_11_10 12_27 pm](https://user-images.githubusercontent.com/11316241/32882471-270f95d6-cabd-11e7-889c-e8ff52a8a651.png)

Для всех пользователей у которых Newsroom Role не NONE (это будут STAFF, MODERATOR, ADMINISTRATOR) в колонке Activity показывать кнопку Activity (красная на скриншоте – сделать стандартную для проекта), при клике на которую будет выезжать точно такая же панелька справа с информацией о пользователе, но вместо комментариев, которые он оставил, должен быть список комментариев, которые он обработал в админке.

![pasted image at 2017_11_10 12_28 pm](https://user-images.githubusercontent.com/11316241/32882488-308d5c60-cabd-11e7-9f2f-ce589581ba83.png)

Сейчас у каждого комментария в mongodb есть поле `status_history`, в котором хранятся такие данные:
```
"status_history" : [ 
        {
            "type" : "NONE",
            "created_at" : ISODate("2017-11-10T08:16:17.024Z"),
            "assigned_by" : null
        }, 
        {
            "created_at" : ISODate("2017-11-10T08:49:45.175Z"),
            "type" : "ACCEPTED",
            "assigned_by" : "e03fca7b-d60f-4fc1-8290-74b9734f8bf8"
        }
],
```
где `assigned_by` - ID пользователя
С помощью такого запроса можно выбрать комментарии конкретного пользователя:
```
db.getCollection('comments').find({"status_history.assigned_by": 'e03fca7b-d60f-4fc1-8290-74b9734f8bf8'})
```
e03fca7b-d60f-4fc1-8290-74b9734f8bf8 – id пользователя

**Comment by racc-oo-n** [comment]
В этом PR https://github.com/Newsi/talk/pull/6 я начала делать задачу
там уже есть кнопка в таблице, и новые компоненты с модалкой
осталось написать выборки для комментариев, где-то в `gql` запросах, эта функция не подойдёт
`db.getCollection('comments').find({"status_history.assigned_by": 'e03fca7b-d60f-4fc1-8290-74b9734f8bf8'})`
как только получится сделать выборку и получать комментарии с нужным `status_history.assigned_by`, то поидее всё должно заработать

**Comment by odynokov** [comment]
@racc-oo-n 
До нас плохо донесли смысл задачи. Я решил уточнить, какую проблему пытаемся решить. Итак, главное - видеть, кто из модераторов какой коментарий одобрил или отклонил.
Эти сведения можно показывать прямо в карточке с комментарием.
В модели Comments уже есть поле `status_history`, в котором есть нужные нам сведения.
Нам нужен последний статус - именно он определяет текущее состояние комментария.

**Comment by odynokov** [comment]
https://github.com/Newsi/talk/commit/0d7ae0bba103d249c5cce2b3ffe404e751ff5288
