### ISSUE TITLE
Перевод на казахский

### ISSUE THREAD

**Issue by odynokov** [Newsi/talk#30]
Добавить перевод на казахский функционала по СМС-регистрации.

**Comment by racc-oo-n** [comment]
Что значит "функционала по СМС-регистрации"? Формочки?
Мне помнится мы уже обсуждали проблему с мультиязычностью – мы не можем из комментариев определять язык. Поэтому там и дисклеймер только на русском.

**Comment by odynokov** [comment]
ОК. Пока что не будем реализовывать. Только в мобильном приложении будет разделение.
Ошибки будут, выходит, только на русском?

**Comment by racc-oo-n** [comment]
Да, всё будет только на русском.
Можно вернуться к старому варианту и отдавать тот язык, который установлен в браузере по-умолчанию. Но тогда всё равно может быть несоответствие языка комментариев и языка сайта.

**Comment by racc-oo-n** [comment]
moved to jira
