### ISSUE TITLE
Номер телефона не подтвержден

### ISSUE THREAD

**Issue by odynokov** [Newsi/talk#31]
Зарегистрированный пользователь с неподтверждённым телефоном никогда не сможет авторизироваться, потому что не сможет подтвердить телефон.

Нужно давать пользователю попасть на странице подтверждения телефона.

**Comment by racc-oo-n** [comment]
Не понимаю проблемы.
Если ты зарегистрирован, но телефон не подтвердил и пытаешься войти, то тебя перекидывает на страницу подтверждения. Так сейчас работает.

**Comment by odynokov** [comment]
Меня не кидало. Просто писало, что номер телефона не подтверждён. Выходит, нужно протестировать повторно.
