### ISSUE TITLE
Номера телефонов модераторов

### ISSUE THREAD

**Issue by odynokov** [Newsi/talk#36]
После полного перехода на СМС-регистрацию добавить номера телефонов модераторов.

aidar1975@mail.ru +7 777 444 21 99
almira7almira@corp.nur.kz +7 747 991 73 47
aliya.absemetova@gmail.com +7 708 908 48 08
marzhan23@gmail.com +7 701 868 20 57
g.kokashbaeva@corp.nur.kz +7 701 254 75 01
indira.jaugasheva@corp.nur.kz +90 539 651 67 88
antipina.lyubov@gmail.com +7 707 814 03 84
pritchinps@gmail.com +7 707 332 39 42

**Comment by racc-oo-n** [comment]
Желательно соотношение email=>phone
они же на почту регистрировались?

**Comment by odynokov** [comment]
Обновил

**Comment by racc-oo-n** [comment]
moved to jira
