### ISSUE TITLE
Добавить столбец с Датой первого просмотра статьи в "Истории" 

### ISSUE THREAD

**Issue by svitlanamykolaienko** [Newsi/talk#37]
### Actual behavior
Сортировка в Истории происходит по дате первого просмотра статьи и видна только дата публикации статьи.
![image](https://user-images.githubusercontent.com/33082028/35553857-384bce30-05a2-11e8-877b-36e384d25e1e.png)
### Steps to reproduce behavior
1. Войти в https://comments.nur.stage.systools.pro/admin/stories
### Expected behavior
В "Истории" добавить столбец с Датой первого просмотра статьи

**Comment by racc-oo-n** [comment]
moved to jira
