### ISSUE TITLE
Время жизни токена

### ISSUE THREAD

**Issue by odynokov** [Newsi/talk#39]
Для мобильных приложений особенно важно время жизни токена.
Будет хорошо выяснить, как работает сейчас токен. Он "протухает" спустя 1 день после создания или же спустя 1 день после отсутствия активности пользователя?
Можем начать с того, что увеличим время жизни до 2 месяцев.

**Comment by odynokov** [comment]
Судя по всему, время жизни токена выставляется в файле `/config.js` в константе `JWT_EXPIRY`.

**Comment by racc-oo-n** [comment]
Может лучше сделать дополнительный параметр в запросе, что-то типа `keepTokenAlive` и поставить бесконечную жизнь токена, иначе использовать `JWT_EXPIRY`

**Comment by odynokov** [comment]
В запросе с клиента?

**Comment by racc-oo-n** [comment]
Ага
Ну или если нам не важно на вебе, то можно действительно сильно увеличить время жизни

**Comment by odynokov** [comment]
Та вот вчера прилетело от модераторов из Казахстана, что их напрягает каждый день авторизироваться. А некоторых выкидывает из системы (разлогинивает) уже часа через два.
Последнее вчера проверили - не воспроизвели.
Самое занятное, что некоторые модераторы пользуются админкой с мобильного телефона :-)

**Comment by racc-oo-n** [comment]
> некоторые модераторы пользуются админкой с мобильного телефона

Им нравится боль? Там же нет мобильной версии.


По поводу токен, он ставится
`JWT_EXPIRY: process.env.TALK_JWT_EXPIRY || '1 day',`

так может @yeo-gen поставит `TALK_JWT_EXPIRY`? или это проблематично и лучше через js?

**Comment by odynokov** [comment]
Напротив, через окружение лучше 👍 
Правда, @yeo-gen ?

**Comment by yeo-gen** [comment]
Так-так - такого роду змінні краще через ENV передавати

**Comment by racc-oo-n** [comment]
переехало в jira
